<!--
  PowerButtonConfig — editor for the new `power_button` item type.

  Differences vs. ButtonConfig:
    - title:    'power_button' instead of 'button'
    - preview:  uses PowerButton (auto-derives state/color)
    - "color":  removed (auto-generated by template.color); per-field templater
                buttons still allow overriding template.* (state, color, ...)
    - new fields: power_sensor, on_color, off_color (stored as top-level on `sel`)
-->
<script lang="ts">
	import {
		dashboard,
		states,
		record,
		lang,
		ripple,
		history,
		historyIndex,
		templates,
		entityList
	} from '$lib/Stores';
	import { onDestroy } from 'svelte';
	import PowerButton from '$lib/Main/PowerButton.svelte';
	import Select from '$lib/Components/Select.svelte';
	import Modal from '$lib/Modal/Index.svelte';
	import Icon from '@iconify/svelte';
	import Ripple from 'svelte-ripple';
	import InputClear from '$lib/Components/InputClear.svelte';
	import ConfigButtons from '$lib/Modal/ConfigButtons.svelte';
	import { updateObj, getDomain, getName, getTogglableService } from '$lib/Utils';
	import type { ButtonItem } from '$lib/Types';
	import { openModal } from 'svelte-modals';
	import parser from 'js-yaml';

	export let isOpen: boolean;
	export let sel: ButtonItem & {
		power_sensor?: string;
		on_color?: string;
		off_color?: string;
	};
	export let demo: string | undefined = undefined;
	export let sectionName: string | undefined = undefined;

	if (demo) {
		// replace history entry with demo
		$history.splice($historyIndex, 1);
		set('entity_id', demo);
	}

	$: entity_id = sel?.entity_id;
	let name = sel?.name;
	let icon = sel?.icon;
	let state = sel?.state;
	let computedIcon: string;

	/**
	 * Push a power-button override field straight into the shared `sel`
	 * object and notify the dashboard store. We bypass updateObj's
	 * event-shaped API and write the plain value, which is what
	 * `<input bind:value=...>` already gives us.
	 *
	 * Setting `undefined`/empty string deletes the key (back to default).
	 * Used by all power-button-specific inputs (text, color, checkbox).
	 */
	function setField(key: string, value: string | boolean | undefined) {
		if (value === undefined || value === '' || value === false) {
			delete (sel as any)[key];
		} else {
			(sel as any)[key] = value;
		}
		sel = sel; // svelte: mark local reactive
		$dashboard = $dashboard; // store: notify subscribers
	}

	/**
	 * Entity picker filter: by default we only offer toggleable entities
	 * (`switch.*`, `light.*`, `input_boolean.*`) that ALSO have a companion
	 * `sensor.<base>_power` in the states tree — those are the entities a
	 * `power_button` is meant to control.
	 *
	 * Without the domain restriction we would also surface things like
	 * `update.foo` whenever `sensor.foo_power` happens to exist, which is
	 * nonsense.
	 *
	 * Edge cases handled:
	 *   - `sel.power_sensor` override → if user picked a custom power sensor,
	 *     the selected entity_id might not be in the filtered list; we
	 *     append it so it doesn't vanish from the dropdown.
	 *   - "Show all entities" toggle (sel.show_all_entities=true) bypasses
	 *     the filter for power-users.
	 */
	const POWER_BUTTON_DOMAINS = ['switch', 'light', 'input_boolean'];

	$: powerCapableOptions = $entityList('').filter((opt: any) => {
		const dot = opt.id.indexOf('.');
		if (dot < 1) return false;
		const domain = opt.id.substring(0, dot);
		if (!POWER_BUTTON_DOMAINS.includes(domain)) return false;
		const base = opt.id.substring(dot + 1);
		return $states?.[`sensor.${base}_power`] !== undefined;
	});

	$: options = sel?.show_all_entities
		? $entityList('')
		: (() => {
				const filtered = powerCapableOptions;
				// preserve currently-selected entity even if it doesn't have a companion sensor
				if (sel?.entity_id && !filtered.some((o: any) => o.id === sel.entity_id)) {
					const all = $entityList('');
					const current = all.find((o: any) => o.id === sel.entity_id);
					if (current) return [...filtered, current].sort((a: any, b: any) => a.id.localeCompare(b.id));
				}
				return filtered;
			})();

	$: template = $templates?.[sel?.id];

	// default placeholders for the new fields, derived from entity_id
	$: derivedBase = entity_id?.includes('.') ? entity_id.split('.')[1] : entity_id;
	$: derivedPowerSensor = derivedBase ? `sensor.${derivedBase}_power` : '';

	function set(key: string, event?: any) {
		// IMPORTANT: keep mutating the SAME object reference. The `sel` passed
		// into this dialog points into the live `$dashboard` tree; replacing
		// it with `{ ...sel }` would detach the local copy from the store, so
		// nothing would be saved on disk.
		sel = updateObj(sel, key, event);
		$dashboard = $dashboard;
	}

	onDestroy(() => $record());

	let servicePlaceholder: string;

	$: if (entity_id || template?.service?.output) updateServicePlaceholder();

	function updateServicePlaceholder() {
		try {
			if (template?.service?.output) {
				const parsed = parser.load(template.service.output) as {
					service: string;
					data: Record<string, any>;
				};
				servicePlaceholder = parsed?.service || $lang('none');
			} else {
				const service = getTogglableService($states[sel?.entity_id]);
				servicePlaceholder = service || $lang('none');
			}
		} catch {
			servicePlaceholder = $lang('error');
		}
	}
</script>

{#if isOpen}
	<Modal>
		<h1 slot="title">{$lang('power_button')}</h1>

		<h2>{$lang('preview')}</h2>

		<div style:pointer-events="none">
			<PowerButton {sel} {sectionName} />
		</div>

		<h2>{$lang('entity')}</h2>

		<div style="display: flex; gap: 0.8rem;">
			<div class="full-width">
				<Select
					{options}
					placeholder={$lang('entity')}
					value={entity_id}
					on:change={(event) => {
						if (event?.detail === null) return;
						set('entity_id', event);
					}}
					computeIcons={true}
					getIconString={true}
					on:iconString={(event) => {
						computedIcon = event?.detail;
					}}
				/>

				<!-- Filter status / opt-out toggle -->
				<label style="display:flex; align-items:center; gap:0.5rem; margin-top:0.5rem; font-size:0.85rem; opacity:0.75;">
					<input
						type="checkbox"
						checked={sel?.show_all_entities === true}
						on:change={(e) => setField('show_all_entities', e.currentTarget.checked)}
					/>
					{$lang('show_all_entities')}
					{#if !sel?.show_all_entities}
						<span style="opacity:0.6;">({powerCapableOptions.length})</span>
					{/if}
				</label>
			</div>

			<button
				use:Ripple={$ripple}
				title={$lang('template')}
				class="icon-gallery"
				on:click={() => {
					if (!sel?.id) return;
					openModal(() => import('$lib/Modal/Templater.svelte'), {
						sel,
						type: 'set_state'
					});
				}}
				style:padding="0.85rem"
				class:template-active={template?.set_state?.output}
			>
				<Icon icon="ph:brackets-curly-bold" height="none" />
			</button>
		</div>

		<h2>{$lang('name')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={name}
				on:clear={() => {
					name = undefined;
					set('name');
				}}
				let:padding
			>
				<input
					name={$lang('name')}
					class="input"
					type="text"
					placeholder={template?.name?.output ||
						getName(sel, (entity_id && $states[entity_id]) || undefined) ||
						$lang('name')}
					autocomplete="off"
					spellcheck="false"
					bind:value={name}
					on:change={(event) => set('name', event)}
					style:padding
					disabled={Boolean(template?.name?.output)}
					class:disabled={Boolean(template?.name?.output)}
				/>
			</InputClear>

			<button
				use:Ripple={$ripple}
				title={$lang('template')}
				class="icon-gallery"
				on:click={async () => {
					if (!sel?.id) return;
					openModal(() => import('$lib/Modal/Templater.svelte'), {
						sel,
						type: 'name'
					});
				}}
				style:padding="0.85rem"
				class:template-active={template?.name?.output}
			>
				<Icon icon="ph:brackets-curly-bold" height="none" /></button
			>
		</div>

		<h2>{$lang('state')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={state}
				on:clear={() => {
					state = undefined;
					set('state');
				}}
				let:padding
			>
				<input
					name={$lang('state')}
					class="input"
					type="text"
					placeholder={template?.state?.output ||
						(entity_id && $states?.[entity_id]?.state) ||
						$lang('state')}
					autocomplete="off"
					spellcheck="false"
					bind:value={state}
					on:change={(event) => set('state', event)}
					style:padding
					disabled={Boolean(template?.state?.output)}
					class:disabled={Boolean(template?.state?.output)}
				/>
			</InputClear>

			<button
				use:Ripple={$ripple}
				title={$lang('template')}
				class="icon-gallery"
				on:click={async () => {
					if (!sel?.id) return;
					openModal(() => import('$lib/Modal/Templater.svelte'), {
						sel,
						type: 'state'
					});
				}}
				style:padding="0.85rem"
				class:template-active={template?.state?.output}
			>
				<Icon icon="ph:brackets-curly-bold" height="none" /></button
			>
		</div>

		<h2>{$lang('icon')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={icon}
				on:clear={() => {
					icon = undefined;
					set('icon');
				}}
				let:padding
			>
				<input
					name={$lang('icon')}
					class="input"
					type="text"
					placeholder={(sel?.template?.icon && template?.icon?.output) ||
						computedIcon ||
						$lang('icon')}
					autocomplete="off"
					spellcheck="false"
					bind:value={icon}
					on:change={(event) => set('icon', event)}
					style:padding
					disabled={Boolean(sel?.template?.icon && template?.icon?.output)}
					class:disabled={Boolean(sel?.template?.icon && template?.icon?.output)}
				/>
			</InputClear>

			<button
				use:Ripple={$ripple}
				title={$lang('icon')}
				class="icon-gallery"
				on:click={() => {
					window.open('https://icon-sets.iconify.design/', '_blank');
				}}
				style:padding="0.84rem"
			>
				<Icon icon="majesticons:open-line" height="none" />
			</button>

			<button
				use:Ripple={$ripple}
				title={$lang('template')}
				class="icon-gallery"
				on:click={() => {
					if (!sel?.id) return;
					openModal(() => import('$lib/Modal/Templater.svelte'), {
						sel,
						type: 'icon'
					});
				}}
				style:padding="0.85rem"
				class:template-active={sel?.template?.icon && template?.icon?.output}
			>
				<Icon icon="ph:brackets-curly-bold" height="none" /></button
			>
		</div>

		<!-- ──── Power button specific fields ──── -->

		<h2>{$lang('power_sensor')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={sel?.power_sensor}
				on:clear={() => setField('power_sensor', undefined)}
				let:padding
			>
				<input
					name={$lang('power_sensor')}
					class="input"
					type="text"
					placeholder={derivedPowerSensor || 'sensor.<base>_power'}
					autocomplete="off"
					spellcheck="false"
					value={sel?.power_sensor || ''}
					on:input={(e) => setField('power_sensor', e.currentTarget.value)}
					style:padding
				/>
			</InputClear>
		</div>

		<h2>{$lang('on_color')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={sel?.on_color}
				on:clear={() => setField('on_color', undefined)}
				let:padding
			>
				<input
					name={$lang('on_color')}
					class="input"
					type="text"
					placeholder="red"
					autocomplete="off"
					spellcheck="false"
					value={sel?.on_color || ''}
					on:input={(e) => setField('on_color', e.currentTarget.value)}
					style:padding
				/>
			</InputClear>

			<input
				type="color"
				value={sel?.on_color && sel.on_color.startsWith('#') ? sel.on_color : '#ff0000'}
				on:input={(e) => setField('on_color', e.currentTarget.value)}
				on:change={(e) => setField('on_color', e.currentTarget.value)}
				title={$lang('on_color')}
			/>
		</div>

		<h2>{$lang('off_color')}</h2>

		<div class="icon-gallery-container">
			<InputClear
				condition={sel?.off_color}
				on:clear={() => setField('off_color', undefined)}
				let:padding
			>
				<input
					name={$lang('off_color')}
					class="input"
					type="text"
					placeholder="grey"
					autocomplete="off"
					spellcheck="false"
					value={sel?.off_color || ''}
					on:input={(e) => setField('off_color', e.currentTarget.value)}
					style:padding
				/>
			</InputClear>

			<input
				type="color"
				value={sel?.off_color && sel.off_color.startsWith('#') ? sel.off_color : '#808080'}
				on:input={(e) => setField('off_color', e.currentTarget.value)}
				on:change={(e) => setField('off_color', e.currentTarget.value)}
				title={$lang('off_color')}
			/>
		</div>

		<!-- ──── /power_button specific ──── -->

		<h2>{$lang('service')}</h2>

		<div class="icon-gallery-container">
			<input
				name={$lang('service')}
				class="input"
				type="text"
				placeholder={servicePlaceholder}
				autocomplete="off"
				spellcheck="false"
				disabled={true}
				class:disabled={true}
			/>

			<button
				use:Ripple={$ripple}
				title={$lang('template')}
				class="icon-gallery"
				on:click={() => {
					if (!sel?.id) return;
					openModal(() => import('$lib/Modal/Templater.svelte'), {
						sel,
						type: 'service'
					});
				}}
				style:padding="0.85rem"
				class:template-active={template?.service?.output}
			>
				<Icon icon="ph:brackets-curly-bold" height="none" /></button
			>
		</div>

		<h2>{$lang('show_more_info')}</h2>

		<div class="button-container">
			<button
				class:selected={sel?.more_info !== false}
				on:click={() => set('more_info')}
				use:Ripple={$ripple}
			>
				{$lang('yes')}
			</button>

			<button
				class:selected={sel?.more_info === false}
				on:click={() => set('more_info', false)}
				use:Ripple={$ripple}
			>
				{$lang('no')}
			</button>
		</div>

		{#if getDomain(entity_id) === 'media_player'}
			<h2>Marquee</h2>

			<div class="button-container">
				<button
					class:selected={!sel?.marquee}
					on:click={() => set('marquee', false)}
					use:Ripple={$ripple}
				>
					{$lang('no')}
				</button>

				<button
					class:selected={sel?.marquee}
					on:click={() => set('marquee', true)}
					use:Ripple={$ripple}
				>
					{$lang('yes')}
				</button>
			</div>
		{/if}

		<ConfigButtons {sel} />
	</Modal>
{/if}

<style>
	input[type='color'] {
		color-scheme: dark;
		height: inherit;
		width: 3.15rem;
		padding: 0;
		-webkit-appearance: none;
		appearance: none;
		background-color: transparent;
		cursor: pointer;
		border: none;
	}

	input[type='color']::-webkit-color-swatch {
		border-radius: 0.6rem;
		border: none;
	}

	input[type='color']::-moz-color-swatch {
		border-radius: 0.6rem;
		border: none;
	}

	.template-active {
		color: rgb(59, 15, 16) !important;
		background-color: rgb(255, 193, 7) !important;
	}

	.disabled {
		opacity: 0.4;
	}

	.full-width {
		width: -webkit-fill-available;
		width: -moz-available;
	}
</style>
